;MODULO DANIEL - ADAPTADO PARA SER LLAMADO DESDE MAIN
; Se llama con: CALL PROCESO_DANIEL
; Retorna con RET al menu principal
;****************************************************************
 
; NOTA: Las variables ya están declaradas en el .DATA del MAIN (systemgarden.asm)
; NO se repiten aquí. Este archivo solo contiene el bloque .CODE del módulo.
 
; ================================================================
; SALTO_LINEA_DAN: declarado aquí como dato local en segmento de código
; ================================================================
; ADVERTENCIA: SALTO_LINEA ya existe en el MAIN, renómbrala si hay conflicto
; Verifica que en el .DATA del main tengas:
;   SALTO_LINEA_DAN  DB 13,10
 
PROCESO_DANIEL PROC
 
;1.- GENERAR MENÚ DE INVENTARIO 
MENU_MAIN_INVENTARIO:
    NEWPAGE
    CURSOR 0,0,0
    FONDO_COLOR 1EH,32
    IMP_COLOR TIT_INV,27,0,0,2,30,090
    IMP_COLOR OP1_INV,14,0,0,6,30,100
    IMP_COLOR OP2_INV,18,0,0,8,30,100
    IMP_COLOR OP3_INV,9,0,0,10,30,100
    IMP_COLOR OP_INV,3,0,0,12,30,100 
 
;1.1- SELECCIONAR OPCIONES EN MENÚ
OP_MAIN_DAN:
    CURSOR 12,35,0
    LECTURA_CADENA OPDB_INV 
    CMP OPDB_INV+2,'1'
    JE INVENTARIO_DAN
    CMP OPDB_INV+2,'2'
    JE RIEGO_DAN
    CMP OPDB_INV+2,'3'
    JE FIN_DANIEL          ; <-- En lugar de JMP FIN del main, retornamos
    JMP ERROR_DAN
  
;2.- SUBMENÚ INVENTARIO
INVENTARIO_DAN:
    NEWPAGE             
    CURSOR 0,0,0        
    FONDO_COLOR 1EH,32
    IMP_COLOR TIT_INV_SUB, 18, 0, 0, 2, 30, 01EH
    IMP_COLOR OP1_INV_SUB, 18, 0, 0, 6, 25, 01EH
    IMP_COLOR OP2_INV_SUB, 20, 0, 0, 8, 25, 01EH
    IMP_COLOR OP3_INV_SUB, 23, 0, 0, 10, 25, 01EH
    IMP_COLOR OP4_INV_SUB, 12, 0, 0, 12, 25, 01EH
    IMP_COLOR OP_MSG_SUB, 4, 0, 0, 15, 25, 01EH
    
INVENTARIO_OP_DAN:
    CURSOR 15, 30, 0
    LECTURA_CADENA OPDB_SUB
    CMP OPDB_SUB+2, '1'
    JE  ADD_RECURSO_DAN
    CMP OPDB_SUB+2, '2'
    JE  READ_DATA_DAN
    CMP OPDB_SUB+2, '3'
    JE  EDIT_DATA_DAN
    CMP OPDB_SUB+2, '4'
    JE  MENU_MAIN_INVENTARIO    ; Regresar al menú de Daniel
    JMP ERROR_INV_DAN
     
;2.5. PANTALLA PARA AÑADIR RECURSOS AL INVENTARIO
ADD_RECURSO_DAN:
    NEWPAGE
    CURSOR 0,0,0
    FONDO_COLOR 1EH,32
 
    CMP CONTADOR_INV,8
    JAE LIMITE_INV_DAN
 
    IMP_COLOR TIT_ADD,21,0,0,2,25,1EH
    IMP_COLOR MSG_RECURSO,9,0,0,6,20,1EH
    
    CURSOR 6,32,0
    LECTURA_CADENA BUFFER_NOMBRE
    
    MOV CX,0
    MOV CL,BUFFER_NOMBRE[1]
    ADD CX,2
    MOV SI,CX
    MOV BUFFER_NOMBRE[SI],0
 
    ; SALIR CON "EXIT"
    CMP BUFFER_NOMBRE+2,'E'
    JNE CONTINUAR_ADD_DAN
    CMP BUFFER_NOMBRE+3,'X'
    JNE CONTINUAR_ADD_DAN
    CMP BUFFER_NOMBRE+4,'I'
    JNE CONTINUAR_ADD_DAN
    CMP BUFFER_NOMBRE+5,'T'
    JNE CONTINUAR_ADD_DAN
    JMP INVENTARIO_DAN
  
;2.6: LECTURA DE CONTENIDO PARA AGREGAR EN TXT
CONTINUAR_ADD_DAN:
    IMP_COLOR MSG_CANTIDAD,10,0,0,8,20,1EH
    CURSOR 8,32,0
    LECTURA_CADENA BUFFER_CANT
    
    MOV CX,0
    MOV CL,BUFFER_CANT[1]
    ADD CX,2
    MOV SI,CX
    MOV BUFFER_CANT[SI],0
 
    CREAR_ARCHIVO RUTA_INV,32
    ABRIR_ARCHIVO RUTA_INV,2
    JC ERROR_ARC_DAN
 
    MOV ID_DAN,AX
    
    ; MOVER PUNTERO AL FINAL
    MOV AH,42H
    MOV AL,02H
    MOV BX,ID_DAN
    MOV CX,0
    MOV DX,0
    INT 21H
      
;2.7.- AÑADIMOS EL CONTENIDO EN TXT
ESCRIBIR_STOCK_DAN:
    MOV BL,[BUFFER_NOMBRE+1]
    MOV BH,0
    ESCRIBIR_ARCHIVO ID_DAN,20,BUFFER_NOMBRE+2
    ESCRIBIR_ARCHIVO ID_DAN,3,ESPACIO
    MOV BL,[BUFFER_CANT+1]
    MOV BH,0
    ESCRIBIR_ARCHIVO ID_DAN,5,BUFFER_CANT+2 
    ESCRIBIR_ARCHIVO ID_DAN,2,SALTO_LINEA    ; Verifica que SALTO_LINEA esté en el .DATA del main
    CERRAR_ARCHIVO ID_DAN
    INC CONTADOR_INV
    JMP ADD_RECURSO_DAN
  
;2.8.- LÍMITE DEL INVENTARIO 
LIMITE_INV_DAN:
    CURSOR 20,15,0
    IMP_SINCOLOR MSJ_LIMITE
    RASTREO
    JMP INVENTARIO_DAN    
 
;2.9- SUBMENÚ DE LECTURA
READ_DATA_DAN:
    NEWPAGE
    CURSOR 0,0,0
    FONDO_COLOR 1EH,32
    IMP_COLOR TIT_READ,29,0,0,2,22,1EH
 
    ABRIR_ARCHIVO RUTA_INV,0
    JC ERROR_ARC_DAN
 
    MOV ID_DAN,AX
    LEER_ARCHIVO ID_DAN,300,BUFFER_LECTURA
    MOV BYTES_LEIDOS,AX 
    
    MOV SI,AX
    MOV BUFFER_LECTURA[SI],'$'
    CERRAR_ARCHIVO ID_DAN 
    
    MOV TOTAL_PRODUCTOS,0
    MOV SI,0
  
CONTAR_PRODUCTOS_DAN:
    CMP SI,BYTES_LEIDOS
    JAE FIN_CONTADOR_DAN
    MOV AL,BUFFER_LECTURA[SI]
    CMP AL,13
    JNE SIGUIENTE_BYTE_DAN
    INC TOTAL_PRODUCTOS
SIGUIENTE_BYTE_DAN:
    INC SI
    JMP CONTAR_PRODUCTOS_DAN
    
;2.10.- ELIMINAR INVENTARIO
EDIT_DATA_DAN:
    CREAR_ARCHIVO RUTA_INV,32
    MOV CONTADOR_INV,0
    MOV TOTAL_PRODUCTOS,0
    CURSOR 20,15,0
    IMP_SINCOLOR MSJ_ELIMINADO
    RASTREO
    JMP INVENTARIO_DAN
 
FIN_CONTADOR_DAN:
    MOV SI,0
    MOV DH,5
    MOV DL,10
 
MOSTRAR_REGISTROS_DAN:
    CMP SI,BYTES_LEIDOS
    JAE FIN_MOSTRAR_DAN
    MOV AH,2
    MOV BH,0
    INT 10H
    MOV AL,BUFFER_LECTURA[SI]
    CMP AL,13
    JE SALTO_LINEA_READ_DAN
    CMP AL,10
    JE CONTINUAR_READ_DAN
    MOV AH,0EH
    MOV BH,0
    INT 10H
    INC DL
 
CONTINUAR_READ_DAN:
    INC SI
    JMP MOSTRAR_REGISTROS_DAN
 
SALTO_LINEA_READ_DAN:
    INC DH
    MOV DL,10
    INC SI
    JMP MOSTRAR_REGISTROS_DAN
 
FIN_MOSTRAR_DAN:
    IMP_COLOR OP1_READ,20,0,0,20,10,1EH
    IMP_COLOR OP2_READ,12,0,0,22,10,1EH
    IMP_COLOR OP_READ,4,0,0,24,10,1EH
 
READ_OP_DAN:
    CURSOR 24,15,0
    LECTURA_CADENA OPDB_READ
    CMP OPDB_READ+2,'1'
    JE LCD_DAN
    CMP OPDB_READ+2,'2'
    JE INVENTARIO_DAN
    JMP READ_OP_DAN 
 
;2.11.- MOSTRAR DATA EN LCD    
LCD_DAN:
    MOV DX,2040H
    MOV AL,'T'
    OUT DX,AL
    INC DX
    MOV AL,'O'
    OUT DX,AL
    INC DX
    MOV AL,'T'
    OUT DX,AL
    INC DX
    MOV AL,'A'
    OUT DX,AL
    INC DX
    MOV AL,'L'
    OUT DX,AL
    INC DX
    MOV AL,' '
    OUT DX,AL
    INC DX
    MOV AL,'I'
    OUT DX,AL
    INC DX
    MOV AL,'N'
    OUT DX,AL
    INC DX
    MOV AL,'S'
    OUT DX,AL
    INC DX
    MOV AL,'U'
    OUT DX,AL
    INC DX
    MOV AL,'M'
    OUT DX,AL
    INC DX
    MOV AL,'O'
    OUT DX,AL
    INC DX
    MOV AL,'S'
    OUT DX,AL
    INC DX
    MOV AL,':'
    OUT DX,AL
    INC DX
    MOV AL,' '
    OUT DX,AL
    INC DX
    MOV AL,TOTAL_PRODUCTOS
    ADD AL,30H
    OUT DX,AL 
    
    ; 2.12.- SALIDA DE LEDS
    MOV DX,2070H
    MOV BL,TOTAL_PRODUCTOS
    CMP BL,0
    JE APAGAR_LEDS_DAN
    MOV AL,1
 
GENERAR_BITS_DAN:
    CMP BL,1
    JE MOSTRAR_LEDS_DAN
    SHL AL,1
    INC AL
    DEC BL
    JMP GENERAR_BITS_DAN
 
MOSTRAR_LEDS_DAN:
    OUT DX,AL
    JMP FIN_LEDS_DAN
 
APAGAR_LEDS_DAN:
    MOV AL,0
    OUT DX,AL
 
FIN_LEDS_DAN:
    CURSOR 26,10,0
    IMP_SINCOLOR MSJ_LCD
    RASTREO
    JMP READ_OP_DAN
    
;3.- MÓDULO DE RIEGO
RIEGO_DAN:
    NEWPAGE
    CURSOR 0,0,0
    FONDO_COLOR 1EH,32
    IMP_COLOR TIT_RIEGO,24,0,0,2,22,1EH
    IMP_COLOR OP1_RIEGO,17,0,0,6,25,1EH
    IMP_COLOR OP2_RIEGO,17,0,0,8,25,1EH
    IMP_COLOR OP3_RIEGO,16,0,0,10,25,1EH
    IMP_COLOR OP4_RIEGO,12,0,0,12,25,1EH
    IMP_COLOR MSG_RIEGO_OP,4,0,0,16,25,1EH
  
RIEGO_OP_DAN:
    CURSOR 16,30,0
    LECTURA_CADENA OPDB_RIEGO
    CMP OPDB_RIEGO+2,'1'
    JE INICIAR_RIEGO_DAN
    CMP OPDB_RIEGO+2,'2'
    JE DETENER_RIEGO_DAN
    CMP OPDB_RIEGO+2,'3'
    JE MENU_BITACORA_DAN
    CMP OPDB_RIEGO+2,'4'
    JE MENU_MAIN_INVENTARIO    ; Regresa al menú de Daniel
    JMP ERROR_RIEGO_DAN
    
;3.2.- PROCESO DE RIEGO
INICIAR_RIEGO_DAN:
    CURSOR 20,20,0
    IMP_SINCOLOR MSJ_RIEGO_ON
 
GIRO_MOTOR_DAN:
ESPERA1_DAN:
    IN AL,7
    TEST AL,10000000B
    JZ ESPERA1_DAN
    MOV AL,00000001B
    OUT 7,AL
ESPERA2_DAN:
    IN AL,7
    TEST AL,10000000B
    JZ ESPERA2_DAN
    MOV AL,00000011B
    OUT 7,AL
ESPERA3_DAN:
    IN AL,7
    TEST AL,10000000B
    JZ ESPERA3_DAN
    MOV AL,00000010B
    OUT 7,AL
ESPERA4_DAN:
    IN AL,7
    TEST AL,10000000B
    JZ ESPERA4_DAN
    MOV AL,00000110B
    OUT 7,AL
ESPERA5_DAN:
    IN AL,7
    TEST AL,10000000B
    JZ ESPERA5_DAN
    MOV AL,00000100B
    OUT 7,AL
ESPERA6_DAN:
    IN AL,7
    TEST AL,10000000B
    JZ ESPERA6_DAN
    MOV AL,00001100B
    OUT 7,AL
ESPERA7_DAN:
    IN AL,7
    TEST AL,10000000B
    JZ ESPERA7_DAN
    MOV AL,00001000B
    OUT 7,AL
ESPERA8_DAN:
    IN AL,7
    TEST AL,10000000B
    JZ ESPERA8_DAN
    MOV AL,00001001B
    OUT 7,AL
 
    MOV AH,01H
    INT 16H
    JZ GIRO_MOTOR_DAN
    MOV AH,00H
    INT 16H
    CMP AL,'2'
    JE DETENER_RIEGO_DAN
    JMP GIRO_MOTOR_DAN
 
;3.4.- APAGAR MOTOR
DETENER_RIEGO_DAN:
    MOV AL, 00H        
    OUT 7, AL
    CURSOR 20,20,0
    IMP_SINCOLOR MSJ_RIEGO_OFF
    RASTREO            
    JMP RIEGO_DAN
 
;4.- BITÁCORA
MENU_BITACORA_DAN:
    NEWPAGE
    CURSOR 0,0,0
    FONDO_COLOR 1EH,32
    IMP_COLOR TIT_BITACORA,18,0,0,2,28,1EH      ; Sin '$' porque IMP_COLOR usa longitud
    IMP_COLOR OP1_BITACORA,22,0,0,6,22,1EH
    IMP_COLOR OP2_BITACORA,18,0,0,8,22,1EH
    IMP_COLOR OP3_BITACORA,14,0,0,10,22,1EH
    IMP_COLOR MSG_BITACORA_OP,4,0,0,14,22,1EH
 
BITACORA_OP_DAN:
    CURSOR 14,28,0
    LECTURA_CADENA OPDB_BITACORA
    CMP OPDB_BITACORA+2,'1'
    JE EDITAR_BITACORA_DAN
    CMP OPDB_BITACORA+2,'2'
    JE MOSTRAR_BITACORA_DAN
    CMP OPDB_BITACORA+2,'3'
    JE RIEGO_DAN
    JMP BITACORA_OP_DAN
 
EDITAR_BITACORA_DAN:
    NEWPAGE
    CURSOR 4,10,0
    IMP_SINCOLOR TIT_BITACORA
    CURSOR 8,5,0
    LECTURA_CADENA BUFFER_BITACORA
    CREAR_ARCHIVO RUTA_BITACORA,32
    ABRIR_ARCHIVO RUTA_BITACORA,2
    JC ERROR_ARC_DAN
    MOV ID_DAN,AX
    MOV AH,42H
    MOV AL,02H
    MOV BX,ID_DAN
    MOV CX,0
    MOV DX,0
    INT 21H
    MOV BL,BUFFER_BITACORA[1]
    MOV BH,0
    ESCRIBIR_ARCHIVO ID_DAN,BX,BUFFER_BITACORA+2
    ESCRIBIR_ARCHIVO ID_DAN,2,SALTO_LINEA
    CERRAR_ARCHIVO ID_DAN
    CURSOR 20,10,0
    IMP_SINCOLOR MSJ_GUARDADO
    RASTREO
    JMP MENU_BITACORA_DAN
 
MOSTRAR_BITACORA_DAN:
    NEWPAGE
    ABRIR_ARCHIVO RUTA_BITACORA,0
    JC NO_EXISTE_BITACORA_DAN
    MOV ID_DAN,AX
    LEER_ARCHIVO ID_DAN,500,LECTURA_BITACORA 
    CMP BYTES_LEIDOS,0
    JE BITACORA_VACIA_DAN
    MOV BYTES_LEIDOS,AX
    MOV SI,AX
    MOV LECTURA_BITACORA[SI],'$'
    CERRAR_ARCHIVO ID_DAN
    CURSOR 2,5,0
    IMP_SINCOLOR TIT_BITACORA
    CURSOR 5,5,0
    IMP_SINCOLOR LECTURA_BITACORA
    RASTREO
    JMP MENU_BITACORA_DAN
 
NO_EXISTE_BITACORA_DAN:
    CURSOR 20,10,0
    IMP_SINCOLOR MSJ_CREAR_BIT
    RASTREO
    JMP MENU_BITACORA_DAN 
 
BITACORA_VACIA_DAN:
    CERRAR_ARCHIVO ID_DAN
    CURSOR 20,10,0
    IMP_SINCOLOR MSJ_BITACORA_VACIA
    RASTREO
    JMP MENU_BITACORA_DAN    
 
; ---- MANEJADORES DE ERROR ----
ERROR_DAN:
    CURSOR 20,20,0
    IMP_SINCOLOR MSJERROR_DAN
    JMP OP_MAIN_DAN
    
ERROR_INV_DAN:
    CURSOR 20,20,0
    IMP_SINCOLOR MSJERRORINV
    JMP INVENTARIO_OP_DAN
    
ERROR_ARC_DAN:
    CURSOR 20,20,0
    IMP_SINCOLOR MSJERRORARC
    JMP FIN_DANIEL          ; Error de archivo -> regresa al menú principal
    
ERROR_RIEGO_DAN:
    CURSOR 20,20,0
    IMP_SINCOLOR MSJ_ERROR_RIEGO
    JMP RIEGO_OP_DAN
 
; ---- PUNTO DE SALIDA DEL MÓDULO ----
FIN_DANIEL:
    RET                     ; <-- Regresa a MENU_PRINCIPAL en el main
 
PROCESO_DANIEL ENDP